
elastic:
  hosts:
    10.0.17.210:
      hostname: elastic
      lan_ip: 10.0.17.210
      nameserver: 10.0.17.4
      gateway: 10.0.17.2
    agent:
      ansible_host: 10.0.17.101

  vars:
    ansible_python_interpreter: /usr/bin/python3
    device: ens192
    prefix: 24 # 10.0.17.0/24
    gateway: 10.0.17.2 # 480-fw
    name_server: 10.0.17.4 #dns server
    domain: charlotte.local #local domain
