- name: Create Deployer User
  hosts: ubuntu
  remote_user: charlotte  # Log in as root first
  become: yes
  tasks:
    - name: ensure deployer user exists
      ansible.builtin.user:
        name: deployer
        state: present
        shell: /bin/bash
        groups: sudo # Adds to sudoers group on Ubuntu
        append: yes